      PROGRAM E1RN
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION R(100)
      CHARACTER*3 ANSWER
10    CONTINUE
C identify program to user
      WRITE(*,*)' Program E1RN demonstrates use '
      WRITE(*,*)' of RNMLCG, RNECUY, RNSTNR'
      WRITE(*,*)' '
C ask for choice of generator
      WRITE(*,*)' Choose '
      WRITE(*,*)' 1 - uniformly distributed random numbers'
      WRITE(*,*)'     generated by RNMLCG'
      WRITE(*,*)' 2 - uniformly distributed random numbers'
      WRITE(*,*)'     generated by RNECUY'
      WRITE(*,*)' 3 - normally distributed random numbers'
      WRITE(*,*)'     generated by RNSTNR'
      WRITE(*,*)' >'
      READ(*,*) ISWIT
C show current seed(s)
      IF(ISWIT.EQ.1) THEN
        CALL RNMSOT(ISEED1)
        WRITE(*,*)' Current seed is ',ISEED1
      ELSE IF(ISWIT.EQ. 2.OR. ISWIT.EQ.3) THEN
        CALL RNE2OT(ISEED1,ISEED2)
        WRITE(*,*)' Current seeds are ',ISEED1,ISEED2
      END IF
C ask for new seed(s)
      WRITE(*,*)' Do you want to enter new seed(s) (y/n)?'
      WRITE(*,*)' >'
      READ(*,'(A)') ANSWER
      IF(ANSWER(1:1).EQ.'Y' .OR. ANSWER(1:1).EQ.'y') THEN
C read new seed(s) and initiate chosen generator
        IF(ISWIT.EQ.1) THEN
          WRITE(*,*)' Enter one integer (>0) as seed'
          WRITE(*,*)' >'
          READ(*,*) ISEED1
          CALL RNMSIN(ISEED1)
        ELSE IF(ISWIT.EQ. 2.OR. ISWIT.EQ.3) THEN
          WRITE(*,*)' Enter two integers (>0) as seeds'
          WRITE(*,*)' >'
          READ(*,*) ISEED1,ISEED2
          CALL RNE2IN(ISEED1,ISEED2)
        END IF
      END IF
C generate and write random numbers
      IF(ISWIT.EQ.1) THEN
        CALL RNMLCG(R,100)
        WRITE(*,*)' Random numbers produced by RNMLCG:'
        WRITE(*,'(1X,5F11.7)')R
      ELSE IF(ISWIT.EQ.2) THEN
        CALL RNECUY(R,100)
        WRITE(*,*)' Random numbers produced by RNECUY:'
        WRITE(*,'(1X,5F11.7)')R
      ELSE IF(ISWIT.EQ.3) THEN
        CALL RNSTNR(R,100)
        WRITE(*,*)' Random numbers produced by RNSTNR:'
        WRITE(*,'(1X,5F11.7)')R
      END IF
C start all over again?
      WRITE(*,*)' Do you want to continue (y/n)?'
      WRITE(*,*)' >'
      READ(*,'(A)') ANSWER
      IF(ANSWER(1:1).EQ.'Y' .OR. ANSWER(1:1).EQ.'y') GO TO 10
      END
