#include <stdio.h>
#include "datsrc.h"

/* Table of constant values */

static integer c__100 = 100;

main(void)
{
    static integer i, iswit, iseed1, iseed2;
    static double r[100];
    static char answer[3];
L10:
/* identify program to user */
    printf("%s\n", "Program E1RN demonstrates use");
    printf("%s\n\n", "of RNMLCG, RNECUY, RNSTNR:");
/* ask for choice of generator */
    printf("%s\n", "Choose:");
    printf("%s\n", "1 - uniformly distributed random numbers");
    printf("%s\n", "    generated by RNMLCG");
    printf("%s\n", "2 - uniformly distributed random numbers");
    printf("%s\n", "    generated by RNECUY");
    printf("%s\n", "3 - normally distributed random numbers");
    printf("%s\n", "    generated by RNSTNR");
    printf("%s", "> ");
    scanf("%li", &iswit);
/* show current seed(s) */
    if (iswit == 1) {
	rnmsot_(&iseed1);
        printf("%s%10li\n", "Current seed is ", iseed1);
    } else if (iswit == 2 || iswit == 3) {
	rne2ot_(&iseed1, &iseed2);
        printf("%s%10li %10li\n", "Current seeds are ", iseed1,iseed2);
    }
/* ask for new seed(s) */
    printf("%s\n", "Do you want to enter new seed(s) (y/n)?");
    printf("%s", "> ");
    scanf("%1s", answer);
    if (*answer == 'Y' || *answer == 'y') {
/* read new seed(s) and initiate chosen generator */
	if (iswit == 1) {
            printf("%s\n", "Enter one integer (>0) as seed:");
            printf("%s", "> ");
            scanf("%li", &iseed1);
	    rnmsin_(&iseed1);
	} else if (iswit == 2 || iswit == 3) {
            printf("%s\n", "Enter two integers (>0) as seeds:");
            printf("%s\n", ">");
            scanf("%li%li", &iseed1, &iseed2);
	    rne2in_(&iseed1, &iseed2);
	}
    }
/* generate and write random numbers */
    if (iswit == 1) {
	rnmlcg_(r, &c__100);
        printf("%s\n", "Random numbers produced by RNMLCG:");
    } else if (iswit == 2) {
	rnecuy_(r, &c__100);
        printf("%s\n", "Random numbers produced by RNECUY:");
    } else if (iswit == 3) {
	rnstnr_(r, &c__100);
        printf("%s\n", "Random numbers produced by RNSTNR:");
    }
    if (iswit >= 1 && iswit <= 3) {
        for (i = 1; i <= 100; ++i) {
            if (i % 5 == 1)
                printf(" ");
            printf("%11.7lf", r[i-1]);
            if (i % 5 == 0)
                printf("\n");
        }
    }
/* start all over again? */
    printf("%s\n", "Do you want to continue (y/n)?");
    printf("%s", "> ");
    scanf("%1s", answer);
    if (*answer == 'Y' || *answer == 'y') {
	goto L10;
    }
    return 0;
} /* main */

