manual:
	pdflatex qsigex_manual.tex
	bibtex qsigex_manual
	pdflatex qsigex_manual.tex
	pdflatex qsigex_manual.tex

clean:
	rm -f *.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.log
	rm -f *.out
	rm -f *.toc
