      DOUBLE PRECISION FUNCTION GBETAF(Z,W)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(BIG=1.D30, EPSILN=1.D-8)
      IF(W.LT.EPSILN) THEN
        GBETAF=BIG
      ELSE
        GBETAF=EXP(GLNGAM(Z)+GLNGAM(W)-GLNGAM(Z+W))
      END IF
      END
