      DOUBLE PRECISION FUNCTION GBINCO(N,K)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(ONE=1.D0)
      IF(K.EQ.0 .OR. N.EQ.0 .OR. K.EQ.N) THEN
        GBINCO=ONE
      ELSE
        AN=DBLE(N)
        AK=DBLE(K)
        ALBINC=GLNGAM(AN+ONE)-GLNGAM(AK+ONE)-GLNGAM(AN-AK+ONE)
        GBINCO=EXP(ALBINC)
        GBINCO=NINT(GBINCO)
      END IF
      END
