      DOUBLE PRECISION FUNCTION LSQGSS(X,NR,T)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION X(NR)
      PARAMETER (ZERO=0.D0,BIG=700.D0)
      ARG=(X(2)-T)**2/(DBLE(2.)*X(3)**2)
      IF (ARG.GT.BIG) THEN
        LSQGSS=ZERO
      ELSE
        LSQGSS=X(1)*EXP(-ARG)
      END IF
      END
