      SUBROUTINE MINCOV(X0,N,NRED,LIST,USERFN,FACT,SCRAT1,SCRAT2,
     +CX,OK)
      PARAMETER(MAXN=50)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION X0(*),LIST(*),CX(NRED,*),SCRAT1(NRED,*),
     +SCRAT2(NRED,*)
      DIMENSION R(MAXN)
      PARAMETER (EPS=1.D-10,ONE=1.D0)
      LOGICAL OK
      EXTERNAL USERFN
      FRAC=0.D0
      MS=NRED
      NS=NRED
      LS=NRED
      CALL AUXHES(X0,SCRAT1,N,NRED,LIST,USERFN)
      CALL MTXUNT(SCRAT2,MS)
      CALL MTXSVD(SCRAT1,SCRAT2,CX,R,MS,NS,LS,FRAC,OK)
      IF(FACT.LT.EPS) THEN
        F=ONE
      ELSE
        F=FACT
      END IF
      CALL MTXMSC(CX,CX,F,NRED,NRED)
      END
