      DOUBLE PRECISION  FUNCTION MINFND(A,X0,XDIR,N,USERFN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(MAXN=50)
      EXTERNAL USERFN
      DIMENSION X0(N),XDIR(N),XLINE(MAXN)
      DO 10 I=1,N
        XLINE(I)=X0(I)+A*XDIR(I)
   10 CONTINUE
      MINFND=USERFN(XLINE,N)
      END
