      DOUBLE PRECISION FUNCTION MINGLS(X,N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION Y(1000)
      DIMENSION X(N)
      COMMON /CMINGS/ Y,NY
      PARAMETER(SQR2PI=2.506628275D0,BIG=-1.D10,TWO=2.D0,
     +SMALL=1.D-10)
      A=SQR2PI*ABS(X(2))
      IF(A.LT.SMALL) THEN
        F=BIG
      ELSE
        F=LOG(A)
      END IF
      MINGLS=DBLE(NY)*F
      DO 10 I=1,NY
        F=(Y(I)-X(1))**2/(TWO*X(2)**2)
        MINGLS=MINGLS+F
   10 CONTINUE
      END
