      SUBROUTINE MINPRB(XMP,XA,YA,XB,YB,XC,YC)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (EPS=1.D-10)
      XBA=XB-XA
      XBC=XB-XC
      F1=XBA*(YB-YC)
      F2=XBC*(YB-YA)
      ANUM=XBA*F1-XBC*F2
      DEN=F1-F2
      DEN=SIGN(MAX(ABS(DEN),EPS),DEN)
      XMP=XB-ANUM/(2.D0*DEN)
      END
