      SUBROUTINE MTXTRP(A,R,M,N)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(M,N),R(N,M)
      DO 20 J=1,N
        DO 10 I=1,M
          R(J,I)=A(I,J)
   10   CONTINUE
   20 CONTINUE
      END
