      SUBROUTINE REGCON(X,B,T,CHI2,P,NR,NF,ETA,CONETA)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION X(NR),B(NR,NR)
      PARAMETER (ZERO=0.D0,ONE=1.D0,HALF=0.5D0)
      PPRIME=HALF*(P+1)
      IF(CHI2.LE.ZERO) THEN
        S=ONE
        FACT=SQSTNR(PPRIME)
      ELSE
        S=SQRT(CHI2/DBLE(NF))
        FACT=SQSTUD(PPRIME,NF)
      END IF
      ETA=ZERO
      CONETA=ZERO
      DO 20 J=1,NR
        D=B(J,1)
        IF(J.GT.1) THEN
          DO 10 K= 2,J
            D=D+B(J,K)*T**(K-1)
   10     CONTINUE
        END IF
        ETA=ETA+X(J)*D
        CONETA=CONETA+D*D
   20 CONTINUE
      CONETA=FACT*S*SQRT(CONETA)
      END
