      DOUBLE PRECISION FUNCTION SCFTST(X,NF1,NF2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ONE=1.D0, HALF=0.5D0)
      ARG=DBLE(NF2)/(DBLE(NF2)+DBLE(NF1)*X)
      A=HALF*DBLE(NF2)
      B=HALF*DBLE(NF1)
      SCFTST=ONE-GINCBT(A,B,ARG)
      END
