      DOUBLE PRECISION FUNCTION SCHYPG(K,N,KK,NN)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER(ZERO=0.D0)
      SCHYPG = ZERO
      IF(K.GT.0) THEN
        DO 10 J=0,K-1
          SCHYPG = SCHYPG + SDHYPG(J,N,KK,NN)
   10   CONTINUE
      END IF
      END
