      DOUBLE PRECISION FUNCTION SCPOIS(K,ALAMBD)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER(ZERO=0.D0)
      SCPOIS = ZERO
      IF(K.GT.0) THEN
        DO 10 J=0,K-1
          SCPOIS=SCPOIS+SDPOIS(J,ALAMBD)
   10   CONTINUE
      END IF
      END
