      DOUBLE PRECISION FUNCTION SCSTNR(X)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ONE=1.D0, ZERO=0.D0, HALF=0.5D0)
      ARG=HALF*(X**2)
      S=ONE
      IF(X.LT.ZERO) S=-ONE
      F=GINCGM(HALF,ARG)
      SCSTNR=HALF*(ONE+S*F)
      END
