      DOUBLE PRECISION FUNCTION SCSTUD(X,N)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ZERO=0.D0, ONE=1.D0, HALF=0.5D0)
      AN=DBLE(N)
      AN2=HALF*AN
      ARG=AN/(AN+X**2)
      A=GINCBT(AN2,HALF,ARG)
      IF(X.GE.ZERO) THEN
        SCSTUD=ONE-HALF*A
      ELSE
        SCSTUD=HALF*A
      END IF
      END
