      DOUBLE PRECISION FUNCTION SDCHI2(X,N)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ONE=1.D0, ZERO=0.D0, HALF=0.5D0, TWO=2.D0)
      IF(X.NE.ZERO .OR. N.GT.2) THEN
        B=GGAMMA(HALF*DBLE(N))*SQRT(TWO**N)
        C=SQRT(X**(N-2))
        E=EXP(-X*HALF)
        SDCHI2=E*C/B
      ELSE
        IF(N.EQ.2) SDCHI2=HALF
        IF(N.EQ.1) SDCHI2=1.D10
      END IF
      END
