      DOUBLE PRECISION FUNCTION SDFTST(X,NF1,NF2)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ONE=1.D0, HALF=0.5D0, ZERO=0.D0)
      AF1=DBLE(NF1)
      AF2=DBLE(NF2)
      AF12=HALF*AF1
      AF22=HALF*AF2
      AFS2=AF12+AF22
      IF(X.LE.ZERO) THEN
        SDFTST=ZERO
      ELSE
        AL=AF12*LOG(AF1/AF2)-AFS2*LOG(ONE+AF1*X/AF2)+(AF12-ONE)*
     +     LOG(X)+GLNGAM(AFS2)-GLNGAM(AF12)-GLNGAM(AF22)
        SDFTST=EXP(AL)
      ENDIF
      END
