      DOUBLE PRECISION FUNCTION SDHYPG(K,N,KK,NN)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER(ZERO=0.D0,ONE=1.D0)
      AN=DBLE(N)
      ANN=DBLE(NN)
      AK=DBLE(K)
      AKK=DBLE(KK)
      AL=AN-AK
      ALL=ANN-AKK
      IF(AK.LE.AKK .AND. AN.LE.ANN .AND. AL.LE.ALL) THEN
          A=GLNGAM(AKK+ONE)-GLNGAM(AK+ONE)-GLNGAM(AKK-AK+ONE)
          B=GLNGAM(ANN+ONE)-GLNGAM(AN+ONE)-GLNGAM(ANN-AN+ONE)
          C=GLNGAM(ALL+ONE)-GLNGAM(AL+ONE)-GLNGAM(ALL-AL+ONE)
          SDHYPG=EXP(A+C-B)
      ELSE
          SDHYPG=ZERO
      END IF
      END
