      DOUBLE PRECISION FUNCTION SDPOIS(K,ALAMBD)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      SDPOIS=EXP(-ALAMBD)
      IF (K.GT.0) THEN
        DO 10 J=1,K
          SDPOIS=SDPOIS*ALAMBD/DBLE(J)
   10   CONTINUE
      END IF
      END
