      DOUBLE PRECISION FUNCTION SDSTNR(X)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (F=0.39894228D0,HALF=0.5D0, BIG=500.D0)
      ARG=-HALF*X**2
      IF(ABS(ARG).GE.BIG) THEN
        SDSTNR=DBLE(0.)
      ELSE
        SDSTNR=F*EXP(ARG)
      END IF
      END
