      DOUBLE PRECISION FUNCTION SDSTUD(X,N)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      PARAMETER (ONE=1.D0, HALF=0.5D0)
      AN=DBLE(N)
      AN2=HALF*AN
      SQAN=SQRT(AN)
      ARG=-AN2-HALF
      A=(ONE+X*X/AN)**ARG
      BETA=GBETAF(HALF,AN2)
      SDSTUD=A/(BETA*SQAN)
      END
