      SUBROUTINE SMERSS(K,CONFID,ALBACK,ALSMIN,ALSPLS,ALSUPR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER(ZERO=0.D0,ONE=1.D0,HALF=0.5D0,EPSILN=1.D-6)
      COMMON /CMSMER/ CALPHA,CADNOM
      EXTERNAL SMZRSS
      ALPHA=ONE-CONFID
      IF(ALBACK.LE.ZERO) CADNOM=ONE
C compute lower limit ALSMIN of confidence region
      IF(K.EQ.0) THEN
        ALSMIN=ZERO
      ELSE
        KK=K
        IF(ALBACK.GT.ZERO) CADNOM=SCPOIS(KK,ALBACK)
        CALPHA=ONE-HALF*ALPHA
        ALS0=ZERO
        ALS1=ONE
        IF(K.GT.0)ALS1=DBLE(K)
        CALL AUXZBR(ALS0,ALS1,SMZRSS,ALBACK,KK,NDUM)
        CALL AUXZFN(ALS0,ALS1,ALSMIN,SMZRSS,ALBACK,KK,NDUM,EPSILN)
      END IF
      CALPHA=HALF*ALPHA
C compute upper limit ALSPLS of confidence region
      KK=K+1
      IF(ALBACK.GT.ZERO) CADNOM=SCPOIS(KK,ALBACK)
      ALS0=ZERO
      ALS1=DBLE(K)
      CALL AUXZBR(ALS0,ALS1,SMZRSS,ALBACK,KK,NDUM)
      CALL AUXZFN(ALS0,ALS1,ALSPLS,SMZRSS,ALBACK,KK,NDUM,EPSILN)
C compute upper limit ALSUPR of parameter
      CALPHA=ALPHA
      KK=K+1
      ALS0=ZERO
      ALS1=DBLE(K)
      CALL AUXZBR(ALS0,ALS1,SMZRSS,ALBACK,KK,NDUM)
      CALL AUXZFN(ALS0,ALS1,ALSUPR,SMZRSS,ALBACK,KK,NDUM,EPSILN)
      END
C-----------------------------------------------------------------
      DOUBLE PRECISION FUNCTION SMZRSS(ALS,ALBACK,K,NDUM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /CMSMER/ CALPHA,CADNOM
      SMZRSS=CALPHA-SCPOIS(K,ALS+ALBACK)/CADNOM
      END
