      SUBROUTINE SMHSFL(HIST,X0,DELX,NX,XIN,WEIGHT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION HIST(*)
      N=INT((XIN-X0)/DELX)+1
      IF (N.GT.0 .AND. N.LE.NX) THEN
        HIST(N)=HIST(N)+WEIGHT
      END IF
      END
