      SUBROUTINE SMHSGR(HIST,X0,DELX,NX,TX,LTX,TY,LTY,CAPT,
     +                  LCAPT,NWS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION HIST(*)
      CHARACTER*(*) TX,TY,CAPT
      CHARACTER*8 NUMSTR
C determine scale on ordinate
      HM=HIST(1)
      DO 10 I =  2, NX
        HM=MAX(HIST(I),HM)
   10 CONTINUE
      WRITE(NUMSTR,'(E8.2)')HM
      READ(NUMSTR(3:3),'(I1)')M1
      READ(NUMSTR(4:4),'(I1)')M2
      N0=0
      N1=M1+1
      N2=0
      IF(N1.GT.9) THEN
        N0=1
        N1=0
      END IF
      WRITE(NUMSTR(1:1),'(I1)')N0
      WRITE(NUMSTR(3:3),'(I1)')N1
      WRITE(NUMSTR(4:4),'(I1)')N2
      READ(NUMSTR,'(E8.2)')SCALE
C graphics
      CALL GROPEN
      CALL GROPWS(NWS)
      X1=X0+DBLE(NX)*DELX
      CALL GRWNCC(X0,X1,0.D0,SCALE)
      CALL GRVWWC(0.1D0,1.1D0,0.1D0,0.75D0)
      CALL GRWNWC(-0.214D0,1.2D0,-0.1D0,0.9D0)
      CALL GRSTFR(NWS,5.D0,0.D0)
      CALL GRFRAM
      CALL GRSCLX(TX,LTX)
      CALL GRSCLY(TY,LTY)
      CALL GRTXTC(1.D0,CAPT,LCAPT)
      CALL GRBOUN
      CALL GRSTCL(2)
      CALL GRHSDR(HIST,X0,DELX,NX)
      CALL GRCLWS(NWS)
      CALL GRCLSE
      END
