      SUBROUTINE SMSDGR(X,Y,N,XA,XB,YA,YB,TX,LTX,TY,LTY,CAPT,
     +                  LCAPT,NWS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION X(*),Y(*)
      CHARACTER*(*) TX,TY,CAPT
      CALL GROPEN
      CALL GROPWS(NWS)
      CALL GRWNCC(XA,XB,YA,YB)
      CALL GRVWWC(0.2D0,.85D0,0.1D0,0.75D0)
      CALL GRWNWC(-0.214D0,1.2D0,-0.1D0,0.9D0)
      CALL GRSTFR(NWS,5.D0,0.D0)
      CALL GRFRAM
      CALL GRSCLX(TX,LTX)
      CALL GRSCLY(TY,LTY)
      CALL GRTXTC(1.D0,CAPT,LCAPT)
      CALL GRBOUN
      CALL GRSTCL(2)
      DO 10 I=1,N
        CALL GRDATP(1,0.1D0,X(I),Y(I),0.D0,0.D0,0.D0)
   10 CONTINUE
      CALL GRCLWS(NWS)
      CALL GRCLSE
      END
